# acme-lsp config
# ~/.config/acme-lsp/config.toml - Linux
# ~/Library/Preferences/Application\ Support/acme-lsp/config.toml - macOS

# acme-lsp source repository: https://github.com/fhs/acme-lsp

# Note that a relative file paths use os.UserCacheDir(), so on Linux
# "some.log" resolves to "$HOME/.cache/acme-lsp/some.log" and on macOS
# "some.log" resolves to "$HOME/Library/Caches/acme-lsp/some.log"

# See https://godoc.org/github.com/fhs/acme-lsp/internal/lsp/acmelsp/config#File
# for more configuration options

[Servers]

	[Servers.pylsp]
	Command = ["bash", "-c", "$HOME/.local/bin/pylsp"]
	StderrFile = "pylsp.stderr.log"
	LogFile = "pylsp.log"

	[Servers.gopls]
	Command = ["gopls", "serve", "-rpc.trace"]
	StderrFile = "gopls.stderr.log"
	LogFile = "gopls.log"
		# These settings get passed to gopls
		[Servers.gopls.Options]
		hoverKind = "FullDocumentation"

	[Servers.rust-analyzer]
	Command = ["rust-analyzer"]
	StderrFile = "rust-analyzer.stderr.log"
	Logfile = "rust-analyzer.log"
		# These settings get passed to rust-analyzer
		[Servers.rust-analyzer.Options]
                # "checkOnSave.enable" = false

[[FilenameHandlers]]
Pattern = "\\.py$"
ServerKey = "pylsp"

[[FilenameHandlers]]
Pattern = "[/\\\\]go\\.mod$"
LanguageID = "go.mod"
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = "[/\\\\]go\\.sum$"
LanguageID = "go.sum"
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = "\\.go$"
LanguageID = "go"
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = "\\.rs$"
ServerKey = "rust-analyzer"
